services:
  whatsapp-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skincare-whatsapp-client
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - whatsapp-session:/app/.wwebjs_auth
      - whatsapp-cache:/app/.wwebjs_cache
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db


volumes:
  whatsapp-session:
    driver: local
  whatsapp-cache:
    driver: local

networks:
  app-network:
    driver: bridge
