services:
  whatsapp-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skincare-whatsapp-client
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - whatsapp-session:/app/.wwebjs_auth
      - whatsapp-cache:/app/.wwebjs_cache
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: skincare-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-skincare_db}
      - MYSQL_USER=${MYSQL_USER:-skincare_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-skincare_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    driver: local
  whatsapp-session:
    driver: local
  whatsapp-cache:
    driver: local

networks:
  app-network:
    driver: bridge
